/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedPrivateExpenseLogInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addEntry"
      | "entryExists"
      | "getCategory"
      | "getEmotion"
      | "getEntry"
      | "getEntryCount"
      | "getEntryDatesInRange"
      | "getLastEntryDate"
      | "getLevel"
      | "protocolId"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "EntryAdded"): EventFragment;

  encodeFunctionData(
    functionFragment: "addEntry",
    values: [
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "entryExists",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCategory",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEmotion",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntry",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntryCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntryDatesInRange",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastEntryDate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLevel",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "addEntry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "entryExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEmotion", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getEntry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEntryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntryDatesInRange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastEntryDate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLevel", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
}

export namespace EntryAddedEvent {
  export type InputTuple = [
    user: AddressLike,
    date: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, date: bigint, timestamp: bigint];
  export interface OutputObject {
    user: string;
    date: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedPrivateExpenseLog extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedPrivateExpenseLog;
  waitForDeployment(): Promise<this>;

  interface: EncryptedPrivateExpenseLogInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addEntry: TypedContractMethod<
    [
      date: BigNumberish,
      encryptedCategory: BytesLike,
      categoryProof: BytesLike,
      encryptedLevel: BytesLike,
      levelProof: BytesLike,
      encryptedEmotion: BytesLike,
      emotionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  entryExists: TypedContractMethod<
    [user: AddressLike, date: BigNumberish],
    [boolean],
    "view"
  >;

  getCategory: TypedContractMethod<
    [user: AddressLike, date: BigNumberish],
    [string],
    "view"
  >;

  getEmotion: TypedContractMethod<
    [user: AddressLike, date: BigNumberish],
    [string],
    "view"
  >;

  getEntry: TypedContractMethod<
    [user: AddressLike, date: BigNumberish],
    [
      [string, string, string, bigint] & {
        category: string;
        level: string;
        emotion: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getEntryCount: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getEntryDatesInRange: TypedContractMethod<
    [user: AddressLike, startDate: BigNumberish, endDate: BigNumberish],
    [bigint[]],
    "view"
  >;

  getLastEntryDate: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getLevel: TypedContractMethod<
    [user: AddressLike, date: BigNumberish],
    [string],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addEntry"
  ): TypedContractMethod<
    [
      date: BigNumberish,
      encryptedCategory: BytesLike,
      categoryProof: BytesLike,
      encryptedLevel: BytesLike,
      levelProof: BytesLike,
      encryptedEmotion: BytesLike,
      emotionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "entryExists"
  ): TypedContractMethod<
    [user: AddressLike, date: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCategory"
  ): TypedContractMethod<
    [user: AddressLike, date: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEmotion"
  ): TypedContractMethod<
    [user: AddressLike, date: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEntry"
  ): TypedContractMethod<
    [user: AddressLike, date: BigNumberish],
    [
      [string, string, string, bigint] & {
        category: string;
        level: string;
        emotion: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEntryCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEntryDatesInRange"
  ): TypedContractMethod<
    [user: AddressLike, startDate: BigNumberish, endDate: BigNumberish],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLastEntryDate"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLevel"
  ): TypedContractMethod<
    [user: AddressLike, date: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "EntryAdded"
  ): TypedContractEvent<
    EntryAddedEvent.InputTuple,
    EntryAddedEvent.OutputTuple,
    EntryAddedEvent.OutputObject
  >;

  filters: {
    "EntryAdded(address,uint256,uint256)": TypedContractEvent<
      EntryAddedEvent.InputTuple,
      EntryAddedEvent.OutputTuple,
      EntryAddedEvent.OutputObject
    >;
    EntryAdded: TypedContractEvent<
      EntryAddedEvent.InputTuple,
      EntryAddedEvent.OutputTuple,
      EntryAddedEvent.OutputObject
    >;
  };
}
